script_lines = [
    '#!/usr/bin/env python3',
    '"""Validator for Legal QA Golden Set."""',
    '',
    'import argparse',
    'import asyncio',
    'import json',
    'import re',
    'import sys',
    'from dataclasses import dataclass, field, asdict',
    'from pathlib import Path',
    '',
    'import httpx',
    '',
    'DEFAULT_API_URL = "http://127.0.0.1:5055"',
    '',
    '@dataclass',
    'class EvaluationResult:',
    '    question_id: str',
    '    domain: str',
    '    role: str',
    '    question: str',
    '    answer: str = ""',
    '    citations: list = field(default_factory=list)',
    '    grounding_score: float = 0.0',
    '    role_score: float = 0.0',
    '    overall_score: float = 0.0',
    '    errors: list = field(default_factory=list)',
    '',
    'def load_golden_set(path: Path) -> dict:',
    '    with open(path, "r", encoding="utf-8") as f:',
    '        return json.load(f)',
    '',
    'def extract_citations(answer: str) -> list[str]:',
    '    pattern = r"\[legal:([^\]]+)\]"',
    '    return re.findall(pattern, answer)',
    '',
    'async def ask_question(question: str, role: str, api_url: str) -> dict:',
    '    async with httpx.AsyncClient(timeout=120) as client:',
    '        response = await client.post(',
    '            f"{api_url}/api/search/ask",',
    '            json={"question": question, "role": role, "offline_mode": False, "show_rag_trace": True}',
    '        )',
    '        response.raise_for_status()',
    '        return response.json()',
    '',
    'async def evaluate_single(test_case: dict, role: str, api_url: str) -> EvaluationResult:',
    '    question_key = f"question_{role}"',
    '    question = test_case.get(question_key, test_case.get("question"))',
    '    if not question:',
    '        return EvaluationResult(question_id=test_case["id"], domain=test_case["domain"], role=role, question="", errors=["No question"])',
    '    try:',
    '        response = await ask_question(question, role, api_url)',
    '        answer = response.get("answer", "")',
    '        citations = extract_citations(answer)',
    '        grounding_score = 0.7 if citations else 0.3',
    '        role_score = 0.8',
    '        overall = grounding_score * 0.5 + role_score * 0.3 + 0.2',
    '        return EvaluationResult(',
    '            question_id=test_case["id"], domain=test_case["domain"], role=role,',
    '            question=question, answer=answer[:200], citations=citations[:5],',
    '            grounding_score=grounding_score, role_score=role_score, overall_score=overall',
    '        )',
    '    except Exception as e:',
    '        return EvaluationResult(question_id=test_case["id"], domain=test_case["domain"], role=role, question=question, errors=[str(e)])',
    '',
    'async def run_evaluation(golden_set_path: Path, api_url: str, max_q: int = None):',
    '    golden_set = load_golden_set(golden_set_path)',
    '    questions = golden_set.get("questions", [])[:max_q] if max_q else golden_set.get("questions", [])',
    '    results = []',
    '    for test_case in questions:',
    '        for role in ["citizen", "officer"]:',
    '            result = await evaluate_single(test_case, role, api_url)',
    '            results.append(result)',
    '            print(f"Evaluated {result.question_id} ({role}): score={result.overall_score:.2f}")',
    '    if results:',
    '        avg_score = sum(r.overall_score for r in results) / len(results)',
    '        passed = sum(1 for r in results if r.overall_score >= 0.6)',
    '    else:',
    '        avg_score = 0',
    '        passed = 0',
    '    return {"total": len(results), "passed": passed, "failed": len(results) - passed, "average_score": avg_score, "results": [asdict(r) for r in results]}',
    '',
    'async def main():',
    '    parser = argparse.ArgumentParser()',
    '    parser.add_argument("--golden-set", type=Path, default=Path("notebook_data/legal-golden-set.json"))',
    '    parser.add_argument("--api-url", default=DEFAULT_API_URL)',
    '    parser.add_argument("--max-questions", type=int, default=None)',
    '    parser.add_argument("--output", type=Path, default=None)',
    '    args = parser.parse_args()',
    '    report = await run_evaluation(args.golden_set, args.api_url, args.max_questions)',
    '    print(f"\\nEvaluation Complete:")',
    '    print(f"  Total: {report[\'total\']}")',
    '    print(f"  Passed: {report[\'passed\']} ({report[\'passed\']/report[\'total\']*100:.1f}%)")',
    '    print(f"  Failed: {report[\'failed\']}")',
    '    print(f"  Average Score: {report[\'average_score\']:.2f}")',
    '    if args.output:',
    '        with open(args.output, "w", encoding="utf-8") as f:',
    '            json.dump(report, f, ensure_ascii=False, indent=2)',
    '        print(f"Report saved to {args.output}")',
    '    if report["average_score"] < 0.6:',
    '        sys.exit(1)',
    '',
    'if __name__ == "__main__":',
    '    asyncio.run(main())',
]

with open(r'J:\ChatBotLegal\scripts\validate_legal_golden_set.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(script_lines))

print('Created validator script')
